package org.sudoku.model;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class ModelTest {

    /**
     * Scenario:
     * This test checks a normal valid editing flow.
     * The player writes values into two editable cells.
     * Then the player uses undo once.
     * The latest move should be undone, but the earlier move should remain.
     * The test also checks that a fixed cell cannot be modified or cleared.
     */
    @Test
    public void testValidEditSingleLevelUndoAndFixedCellProtection() {
        Model model = createFreshModel();

        Cell editableA = findFirstEditableCell(model);
        Cell editableB = findAnotherEditableCell(model, editableA);
        Cell fixed = findFirstFixedCell(model);

        assertNotNull(editableA, "There should be at least one editable cell.");
        assertNotNull(editableB, "There should be a second editable cell.");
        assertNotNull(fixed, "There should be at least one fixed cell.");

        int fixedOriginal = model.getCellValue(fixed.row, fixed.col);

        assertFalse(model.canUndo(), "Undo should not be available at the start.");

        assertTrue(model.setValue(editableA.row, editableA.col, 4),
                "Writing to an editable cell should be accepted.");
        assertEquals(4, model.getCellValue(editableA.row, editableA.col),
                "The first editable cell should store the written value.");
        assertTrue(model.canUndo(),
                "A successful write should create one undo record.");

        assertTrue(model.setValue(editableB.row, editableB.col, 7),
                "A second write to another editable cell should also be accepted.");
        assertEquals(7, model.getCellValue(editableB.row, editableB.col),
                "The second editable cell should store the written value.");

        assertTrue(model.undo(),
                "Undo should revert the latest accepted move.");
        assertEquals(0, model.getCellValue(editableB.row, editableB.col),
                "The second move should be undone.");
        assertEquals(4, model.getCellValue(editableA.row, editableA.col),
                "The earlier move should remain, proving single-level undo.");
        assertFalse(model.canUndo(),
                "After one successful single-level undo, no more undo should remain.");

        assertFalse(model.setValue(fixed.row, fixed.col, 9),
                "A fixed cell must not accept a new value.");
        assertEquals(fixedOriginal, model.getCellValue(fixed.row, fixed.col),
                "A rejected write must not change the fixed cell.");

        assertFalse(model.clearValue(fixed.row, fixed.col),
                "A fixed cell must not be cleared.");
        assertEquals(fixedOriginal, model.getCellValue(fixed.row, fixed.col),
                "A rejected clear must not change the fixed cell.");
    }

    /**
     * Scenario:
     * This test checks an invalid board-state scenario.
     * The player places the same digit into two editable cells in the same row.
     * The board should become invalid.
     * Those editable cells should be marked invalid.
     * The puzzle must not be treated as solved.
     * No completion event should be produced by this temporary invalid state.
     */
    @Test
    public void testDuplicateDetectionDoesNotTriggerCompletion() {
        Model model = createFreshModel();

        DuplicateScenario scenario = findRowWithTwoEditableCells(model);
        assertNotNull(scenario, "There should be a row with at least two editable cells.");

        int duplicateValue = 5;

        assertTrue(model.setValue(scenario.first.row, scenario.first.col, duplicateValue),
                "The first duplicate write should be accepted.");
        assertTrue(model.setValue(scenario.second.row, scenario.second.col, duplicateValue),
                "The second duplicate write should also be accepted.");

        assertFalse(model.isBoardValid(),
                "The board should become invalid after creating a duplicate.");
        assertTrue(model.isCellInvalid(scenario.first.row, scenario.first.col),
                "The first duplicated editable cell should be marked invalid.");
        assertTrue(model.isCellInvalid(scenario.second.row, scenario.second.col),
                "The second duplicated editable cell should be marked invalid.");

        assertFalse(model.isSolved(),
                "A temporary invalid board must not be treated as solved.");
        assertFalse(model.consumeCompletionEvent(),
                "No completion event should be generated by an invalid state.");
    }

    /**
     * Scenario:
     * This test checks a completion-flow scenario.
     * The test applies hints to all eligible editable cells until the puzzle is solved.
     * After the final correct completion, the model should report solved.
     * The completion event should be available exactly once.
     * Then reset should restore the initial puzzle state and clear solved and undo state.
     */
    @Test
    public void testHintSolveCompletionEventAndReset() {
        Model model = createFreshModel();
        int[][] initialSnapshot = snapshotBoard(model);

        assertFalse(model.isSolved(),
                "A fresh puzzle should not start solved.");
        assertFalse(model.consumeCompletionEvent(),
                "A fresh puzzle should not have a pending completion event.");

        int appliedHints = fillAllEditableCellsWithHints(model);
        assertTrue(appliedHints > 0,
                "At least one hint should have been applied.");

        assertTrue(model.isSolved(),
                "After hinting every eligible cell, the puzzle should be solved.");
        assertTrue(model.consumeCompletionEvent(),
                "The completion event should be available once after solving.");
        assertFalse(model.consumeCompletionEvent(),
                "The completion event should be one-shot only.");

        assertTrue(model.canUndo(),
                "The latest hint should leave one undo record.");

        assertTrue(model.reset(),
                "Reset should succeed.");
        assertFalse(model.isSolved(),
                "Reset must not leave the puzzle solved.");
        assertFalse(model.canUndo(),
                "Reset must clear undo history.");
        assertFalse(model.consumeCompletionEvent(),
                "Reset must not generate a completion event.");

        assertBoardEquals(initialSnapshot, model);
    }

    /*@
      @ public normal_behavior
      @ requires true;
      @ ensures \result != null;
      @ ensures !\result.isSolved();
      @ ensures !\result.canUndo();
      @*/
    private Model createFreshModel() {
        Model model = new Model();

        assert model != null : "A fresh model must be created.";
        assert !model.isSolved() : "A fresh model should not start solved.";
        assert !model.canUndo() : "A fresh model should not start with undo history.";

        return model;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ ensures \result == null
      @      || (0 <= \result.row && \result.row < Model.SIZE
      @      && 0 <= \result.col && \result.col < Model.SIZE
      @      && model.canBeEdit(\result.row, \result.col));
      @*/
    private Cell findFirstEditableCell(Model model) {
        assert model != null : "Model must not be null.";

        Cell result = null;
        for (int row = 0; row < Model.SIZE && result == null; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                if (model.canBeEdit(row, col)) {
                    result = new Cell(row, col);
                    break;
                }
            }
        }

        assert result == null
                || (0 <= result.row && result.row < Model.SIZE
                && 0 <= result.col && result.col < Model.SIZE
                && model.canBeEdit(result.row, result.col))
                : "Returned cell must be an editable in-range cell.";

        return result;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ requires first != null;
      @ ensures \result == null
      @      || (0 <= \result.row && \result.row < Model.SIZE
      @      && 0 <= \result.col && \result.col < Model.SIZE
      @      && model.canBeEdit(\result.row, \result.col)
      @      && (\result.row != first.row || \result.col != first.col));
      @*/
    private Cell findAnotherEditableCell(Model model, Cell first) {
        assert model != null : "Model must not be null.";
        assert first != null : "The first cell must not be null.";
        assert 0 <= first.row && first.row < Model.SIZE : "First cell row must be in range.";
        assert 0 <= first.col && first.col < Model.SIZE : "First cell column must be in range.";

        Cell result = null;
        for (int row = 0; row < Model.SIZE && result == null; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                if (model.canBeEdit(row, col) && (row != first.row || col != first.col)) {
                    result = new Cell(row, col);
                    break;
                }
            }
        }

        assert result == null
                || (0 <= result.row && result.row < Model.SIZE
                && 0 <= result.col && result.col < Model.SIZE
                && model.canBeEdit(result.row, result.col)
                && (result.row != first.row || result.col != first.col))
                : "Returned cell must be another editable in-range cell.";

        return result;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ ensures \result == null
      @      || (0 <= \result.row && \result.row < Model.SIZE
      @      && 0 <= \result.col && \result.col < Model.SIZE
      @      && model.isFixed(\result.row, \result.col));
      @*/
    private Cell findFirstFixedCell(Model model) {
        assert model != null : "Model must not be null.";

        Cell result = null;
        for (int row = 0; row < Model.SIZE && result == null; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                if (model.isFixed(row, col)) {
                    result = new Cell(row, col);
                    break;
                }
            }
        }

        assert result == null
                || (0 <= result.row && result.row < Model.SIZE
                && 0 <= result.col && result.col < Model.SIZE
                && model.isFixed(result.row, result.col))
                : "Returned cell must be a fixed in-range cell.";

        return result;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ ensures \result == null
      @      || (\result.first != null
      @      && \result.second != null
      @      && \result.first.row == \result.second.row
      @      && \result.first.col != \result.second.col
      @      && model.canBeEdit(\result.first.row, \result.first.col)
      @      && model.canBeEdit(\result.second.row, \result.second.col));
      @*/
    private DuplicateScenario findRowWithTwoEditableCells(Model model) {
        assert model != null : "Model must not be null.";

        DuplicateScenario result = null;

        for (int row = 0; row < Model.SIZE && result == null; row++) {
            List<Cell> editableCells = new ArrayList<>();
            for (int col = 0; col < Model.SIZE; col++) {
                if (model.canBeEdit(row, col)) {
                    editableCells.add(new Cell(row, col));
                }
            }
            if (editableCells.size() >= 2) {
                result = new DuplicateScenario(editableCells.get(0), editableCells.get(1));
            }
        }

        assert result == null
                || (result.first != null
                && result.second != null
                && result.first.row == result.second.row
                && result.first.col != result.second.col
                && model.canBeEdit(result.first.row, result.first.col)
                && model.canBeEdit(result.second.row, result.second.col))
                : "Returned scenario must contain two different editable cells in the same row.";

        return result;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ ensures \result != null;
      @ ensures \result.length == Model.SIZE;
      @ ensures (\forall int r; 0 <= r && r < Model.SIZE; \result[r] != null && \result[r].length == Model.SIZE);
      @ ensures (\forall int r, c; 0 <= r && r < Model.SIZE && 0 <= c && c < Model.SIZE;
      @             \result[r][c] == model.getCellValue(r, c));
      @*/
    private int[][] snapshotBoard(Model model) {
        assert model != null : "Model must not be null.";

        int[][] boardCopy = new int[Model.SIZE][Model.SIZE];
        for (int row = 0; row < Model.SIZE; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                boardCopy[row][col] = model.getCellValue(row, col);
            }
        }

        assert boardCopy != null : "Board must not be null.";
        assert boardCopy.length == Model.SIZE : "Board row count must be 9.";

        for (int row = 0; row < Model.SIZE; row++) {
            assert boardCopy[row] != null : "Each boardCopy row must exist.";
            assert boardCopy[row].length == Model.SIZE : "Each boardCopy row must have length 9.";
            for (int col = 0; col < Model.SIZE; col++) {
                assert boardCopy[row][col] == model.getCellValue(row, col)
                        : "Snapshot must match the model state.";
            }
        }

        return boardCopy;
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ requires expected != null;
      @ requires expected.length == Model.SIZE;
      @ requires (\forall int r; 0 <= r && r < Model.SIZE; expected[r] != null && expected[r].length == Model.SIZE);
      @ ensures true;
      @*/
    private void assertBoardEquals(int[][] expected, Model model) {
        assert model != null : "Model must not be null.";
        assert expected != null : "Expected board must not be null.";
        assert expected.length == Model.SIZE : "Expected board row count must be 9.";

        for (int row = 0; row < Model.SIZE; row++) {
            assert expected[row] != null : "Each expected row must exist.";
            assert expected[row].length == Model.SIZE : "Each expected row must have length 9.";
        }

        for (int row = 0; row < Model.SIZE; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                assertEquals(expected[row][col], model.getCellValue(row, col),
                        "Board mismatch at (" + row + "," + col + ").");
            }
        }
    }

    /*@
      @ public normal_behavior
      @ requires model != null;
      @ ensures \result >= 0;
      @ ensures (\forall int r, c; 0 <= r && r < Model.SIZE && 0 <= c && c < Model.SIZE;
      @             !model.canApplyHint(r, c));
      @*/
    private int fillAllEditableCellsWithHints(Model model) {
        assert model != null : "Model must not be null.";

        int count = 0;
        for (int row = 0; row < Model.SIZE; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                if (model.canApplyHint(row, col)) {
                    boolean applied = model.applyHint(row, col);
                    assert applied : "Applying a hint to an eligible cell should succeed.";
                    count++;
                }
            }
        }

        assert count >= 0 : "Hint count must not be negative.";
        for (int row = 0; row < Model.SIZE; row++) {
            for (int col = 0; col < Model.SIZE; col++) {
                assert !model.canApplyHint(row, col)
                        : "After filling all eligible cells with hints, no hintable cell should remain.";
            }
        }

        return count;
    }

    private static final class Cell {
        private final int row;
        private final int col;

        private Cell(int row, int col) {
            assert 0 <= row && row < Model.SIZE : "Cell row must be in range.";
            assert 0 <= col && col < Model.SIZE : "Cell column must be in range.";

            this.row = row;
            this.col = col;

            assert this.row == row : "Stored row must match input row.";
            assert this.col == col : "Stored column must match input column.";
        }
    }

    private static final class DuplicateScenario {
        private final Cell first;
        private final Cell second;

        private DuplicateScenario(Cell first, Cell second) {
            assert first != null : "First cell must not be null.";
            assert second != null : "Second cell must not be null.";
            assert first.row == second.row : "Both cells must be in the same row.";
            assert first.col != second.col : "The two cells must be different.";

            this.first = first;
            this.second = second;

            assert this.first == first : "Stored first cell must match input.";
            assert this.second == second : "Stored second cell must match input.";
        }
    }
}